# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetSegmentsResult',
    'AwaitableGetSegmentsResult',
    'get_segments',
]

@pulumi.output_type
class GetSegmentsResult:
    """
    A collection of values returned by getSegments.
    """
    def __init__(__self__, id=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")


class AwaitableGetSegmentsResult(GetSegmentsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetSegmentsResult(
            id=self.id)


def get_segments(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetSegmentsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('vantage:index/getSegments:getSegments', __args__, opts=opts, typ=GetSegmentsResult).value

    return AwaitableGetSegmentsResult(
        id=__ret__.id)
