# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
from . import outputs

__all__ = [
    'SavedFiltersResult',
    'AwaitableSavedFiltersResult',
    'saved_filters',
]

@pulumi.output_type
class SavedFiltersResult:
    """
    A collection of values returned by SavedFilters.
    """
    def __init__(__self__, filters=None, id=None):
        if filters and not isinstance(filters, list):
            raise TypeError("Expected argument 'filters' to be a list")
        pulumi.set(__self__, "filters", filters)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)

    @property
    @pulumi.getter
    def filters(self) -> Sequence['outputs.SavedFiltersFilterResult']:
        return pulumi.get(self, "filters")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")


class AwaitableSavedFiltersResult(SavedFiltersResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return SavedFiltersResult(
            filters=self.filters,
            id=self.id)


def saved_filters(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableSavedFiltersResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('vantage:index/savedFilters:SavedFilters', __args__, opts=opts, typ=SavedFiltersResult).value

    return AwaitableSavedFiltersResult(
        filters=__ret__.filters,
        id=__ret__.id)
