// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vantage;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.vantage.AccessGrantArgs;
import com.pulumi.vantage.Utilities;
import com.pulumi.vantage.inputs.AccessGrantState;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * Manages an AccessGrant.
 * 
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.vantage.AccessGrant;
 * import com.pulumi.vantage.AccessGrantArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var demoAccessGrant = new AccessGrant(&#34;demoAccessGrant&#34;, AccessGrantArgs.builder()        
 *             .resourceToken(&#34;rprt_39d256c871cb6b2b&#34;)
 *             .teamToken(&#34;team_bd5c2d8abc233bfd&#34;)
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 */
@ResourceType(type="vantage:index/accessGrant:AccessGrant")
public class AccessGrant extends com.pulumi.resources.CustomResource {
    /**
     * Access level of the grant. Must be either `allowed` or `denied`.
     * 
     */
    @Export(name="access", type=String.class, parameters={})
    private Output<String> access;

    /**
     * @return Access level of the grant. Must be either `allowed` or `denied`.
     * 
     */
    public Output<String> access() {
        return this.access;
    }
    /**
     * Token of the resource being granted.
     * 
     */
    @Export(name="resourceToken", type=String.class, parameters={})
    private Output<String> resourceToken;

    /**
     * @return Token of the resource being granted.
     * 
     */
    public Output<String> resourceToken() {
        return this.resourceToken;
    }
    /**
     * Token of the team being granted.
     * 
     */
    @Export(name="teamToken", type=String.class, parameters={})
    private Output<String> teamToken;

    /**
     * @return Token of the team being granted.
     * 
     */
    public Output<String> teamToken() {
        return this.teamToken;
    }
    /**
     * Token of the access grant.
     * 
     */
    @Export(name="token", type=String.class, parameters={})
    private Output<String> token;

    /**
     * @return Token of the access grant.
     * 
     */
    public Output<String> token() {
        return this.token;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public AccessGrant(String name) {
        this(name, AccessGrantArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public AccessGrant(String name, AccessGrantArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public AccessGrant(String name, AccessGrantArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("vantage:index/accessGrant:AccessGrant", name, args == null ? AccessGrantArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private AccessGrant(String name, Output<String> id, @Nullable AccessGrantState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("vantage:index/accessGrant:AccessGrant", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static AccessGrant get(String name, Output<String> id, @Nullable AccessGrantState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new AccessGrant(name, id, state, options);
    }
}
