// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vantage;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.vantage.AwsProviderArgs;
import com.pulumi.vantage.Utilities;
import com.pulumi.vantage.inputs.AwsProviderState;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages an AWS Account Integration.
 * 
 */
@ResourceType(type="vantage:index/awsProvider:AwsProvider")
public class AwsProvider extends com.pulumi.resources.CustomResource {
    /**
     * Bucket ARN for where CUR data is being stored.
     * 
     */
    @Export(name="bucketArn", type=String.class, parameters={})
    private Output</* @Nullable */ String> bucketArn;

    /**
     * @return Bucket ARN for where CUR data is being stored.
     * 
     */
    public Output<Optional<String>> bucketArn() {
        return Codegen.optional(this.bucketArn);
    }
    /**
     * ARN to use for cross account access.
     * 
     */
    @Export(name="crossAccountArn", type=String.class, parameters={})
    private Output<String> crossAccountArn;

    /**
     * @return ARN to use for cross account access.
     * 
     */
    public Output<String> crossAccountArn() {
        return this.crossAccountArn;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public AwsProvider(String name) {
        this(name, AwsProviderArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public AwsProvider(String name, AwsProviderArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public AwsProvider(String name, AwsProviderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("vantage:index/awsProvider:AwsProvider", name, args == null ? AwsProviderArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private AwsProvider(String name, Output<String> id, @Nullable AwsProviderState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("vantage:index/awsProvider:AwsProvider", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static AwsProvider get(String name, Output<String> id, @Nullable AwsProviderState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new AwsProvider(name, id, state, options);
    }
}
