// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vantage;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.resources.InvokeArgs;
import com.pulumi.vantage.Utilities;
import com.pulumi.vantage.outputs.GetAwsProviderInfoResult;
import com.pulumi.vantage.outputs.SavedFiltersResult;
import java.util.concurrent.CompletableFuture;

public final class VantageFunctions {
    public static Output<GetAwsProviderInfoResult> getAwsProviderInfo() {
        return getAwsProviderInfo(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetAwsProviderInfoResult> getAwsProviderInfoPlain() {
        return getAwsProviderInfoPlain(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    public static Output<GetAwsProviderInfoResult> getAwsProviderInfo(InvokeArgs args) {
        return getAwsProviderInfo(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetAwsProviderInfoResult> getAwsProviderInfoPlain(InvokeArgs args) {
        return getAwsProviderInfoPlain(args, InvokeOptions.Empty);
    }
    public static Output<GetAwsProviderInfoResult> getAwsProviderInfo(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("vantage:index/getAwsProviderInfo:getAwsProviderInfo", TypeShape.of(GetAwsProviderInfoResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetAwsProviderInfoResult> getAwsProviderInfoPlain(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("vantage:index/getAwsProviderInfo:getAwsProviderInfo", TypeShape.of(GetAwsProviderInfoResult.class), args, Utilities.withVersion(options));
    }
    public static Output<SavedFiltersResult> savedFilters() {
        return savedFilters(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    public static CompletableFuture<SavedFiltersResult> savedFiltersPlain() {
        return savedFiltersPlain(InvokeArgs.Empty, InvokeOptions.Empty);
    }
    public static Output<SavedFiltersResult> savedFilters(InvokeArgs args) {
        return savedFilters(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<SavedFiltersResult> savedFiltersPlain(InvokeArgs args) {
        return savedFiltersPlain(args, InvokeOptions.Empty);
    }
    public static Output<SavedFiltersResult> savedFilters(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("vantage:index/savedFilters:SavedFilters", TypeShape.of(SavedFiltersResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<SavedFiltersResult> savedFiltersPlain(InvokeArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("vantage:index/savedFilters:SavedFilters", TypeShape.of(SavedFiltersResult.class), args, Utilities.withVersion(options));
    }
}
