// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vantage

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetAwsProviderInfo(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetAwsProviderInfoResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetAwsProviderInfoResult
	err := ctx.Invoke("vantage:index/getAwsProviderInfo:getAwsProviderInfo", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getAwsProviderInfo.
type GetAwsProviderInfoResult struct {
	// The policy that allows Vantage to list and describe resources from your AWS account.
	AdditionalResourcesPolicy string `pulumi:"additionalResourcesPolicy"`
	// The policy that allows Vantage to manage autopilot.
	AutopilotPolicy string `pulumi:"autopilotPolicy"`
	// The policy that allows Vantage to retrieve cloudwatch metrics from your AWS account.
	CloudwatchMetricsPolicy string `pulumi:"cloudwatchMetricsPolicy"`
	// The Vantage external ID to authenticate your account.
	ExternalId string `pulumi:"externalId"`
	// The IAM role that Vantage assumes into your account.
	IamRoleArn string `pulumi:"iamRoleArn"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The policy that allows Vantage to manage autopilot.
	RootPolicy string `pulumi:"rootPolicy"`
}
