// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vantage

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetCostReports(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetCostReportsResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetCostReportsResult
	err := ctx.Invoke("vantage:index/getCostReports:getCostReports", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getCostReports.
type GetCostReportsResult struct {
	CostReports []GetCostReportsCostReport `pulumi:"costReports"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
}
