// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vantage

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetWorkspaces(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetWorkspacesResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetWorkspacesResult
	err := ctx.Invoke("vantage:index/getWorkspaces:getWorkspaces", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getWorkspaces.
type GetWorkspacesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id         string                   `pulumi:"id"`
	Workspaces []GetWorkspacesWorkspace `pulumi:"workspaces"`
}
