// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vantage

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "vantage:index/accessGrant:AccessGrant":
		r = &AccessGrant{}
	case "vantage:index/awsProvider:AwsProvider":
		r = &AwsProvider{}
	case "vantage:index/costReport:CostReport":
		r = &CostReport{}
	case "vantage:index/dashboard:Dashboard":
		r = &Dashboard{}
	case "vantage:index/folder:Folder":
		r = &Folder{}
	case "vantage:index/savedFilter:SavedFilter":
		r = &SavedFilter{}
	case "vantage:index/segment:Segment":
		r = &Segment{}
	case "vantage:index/team:Team":
		r = &Team{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:vantage" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, _ := PkgVersion()
	pulumi.RegisterResourceModule(
		"vantage",
		"index/accessGrant",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"vantage",
		"index/awsProvider",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"vantage",
		"index/costReport",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"vantage",
		"index/dashboard",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"vantage",
		"index/folder",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"vantage",
		"index/savedFilter",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"vantage",
		"index/segment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"vantage",
		"index/team",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"vantage",
		&pkg{version},
	)
}
