// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package vantage

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SavedFiltersFilter struct {
	CostReportTokens []string `pulumi:"costReportTokens"`
	Title            string   `pulumi:"title"`
	Token            string   `pulumi:"token"`
	WorkspaceToken   string   `pulumi:"workspaceToken"`
}

// SavedFiltersFilterInput is an input type that accepts SavedFiltersFilterArgs and SavedFiltersFilterOutput values.
// You can construct a concrete instance of `SavedFiltersFilterInput` via:
//
//	SavedFiltersFilterArgs{...}
type SavedFiltersFilterInput interface {
	pulumi.Input

	ToSavedFiltersFilterOutput() SavedFiltersFilterOutput
	ToSavedFiltersFilterOutputWithContext(context.Context) SavedFiltersFilterOutput
}

type SavedFiltersFilterArgs struct {
	CostReportTokens pulumi.StringArrayInput `pulumi:"costReportTokens"`
	Title            pulumi.StringInput      `pulumi:"title"`
	Token            pulumi.StringInput      `pulumi:"token"`
	WorkspaceToken   pulumi.StringInput      `pulumi:"workspaceToken"`
}

func (SavedFiltersFilterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*SavedFiltersFilter)(nil)).Elem()
}

func (i SavedFiltersFilterArgs) ToSavedFiltersFilterOutput() SavedFiltersFilterOutput {
	return i.ToSavedFiltersFilterOutputWithContext(context.Background())
}

func (i SavedFiltersFilterArgs) ToSavedFiltersFilterOutputWithContext(ctx context.Context) SavedFiltersFilterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SavedFiltersFilterOutput)
}

// SavedFiltersFilterArrayInput is an input type that accepts SavedFiltersFilterArray and SavedFiltersFilterArrayOutput values.
// You can construct a concrete instance of `SavedFiltersFilterArrayInput` via:
//
//	SavedFiltersFilterArray{ SavedFiltersFilterArgs{...} }
type SavedFiltersFilterArrayInput interface {
	pulumi.Input

	ToSavedFiltersFilterArrayOutput() SavedFiltersFilterArrayOutput
	ToSavedFiltersFilterArrayOutputWithContext(context.Context) SavedFiltersFilterArrayOutput
}

type SavedFiltersFilterArray []SavedFiltersFilterInput

func (SavedFiltersFilterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SavedFiltersFilter)(nil)).Elem()
}

func (i SavedFiltersFilterArray) ToSavedFiltersFilterArrayOutput() SavedFiltersFilterArrayOutput {
	return i.ToSavedFiltersFilterArrayOutputWithContext(context.Background())
}

func (i SavedFiltersFilterArray) ToSavedFiltersFilterArrayOutputWithContext(ctx context.Context) SavedFiltersFilterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SavedFiltersFilterArrayOutput)
}

type SavedFiltersFilterOutput struct{ *pulumi.OutputState }

func (SavedFiltersFilterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*SavedFiltersFilter)(nil)).Elem()
}

func (o SavedFiltersFilterOutput) ToSavedFiltersFilterOutput() SavedFiltersFilterOutput {
	return o
}

func (o SavedFiltersFilterOutput) ToSavedFiltersFilterOutputWithContext(ctx context.Context) SavedFiltersFilterOutput {
	return o
}

func (o SavedFiltersFilterOutput) CostReportTokens() pulumi.StringArrayOutput {
	return o.ApplyT(func(v SavedFiltersFilter) []string { return v.CostReportTokens }).(pulumi.StringArrayOutput)
}

func (o SavedFiltersFilterOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v SavedFiltersFilter) string { return v.Title }).(pulumi.StringOutput)
}

func (o SavedFiltersFilterOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v SavedFiltersFilter) string { return v.Token }).(pulumi.StringOutput)
}

func (o SavedFiltersFilterOutput) WorkspaceToken() pulumi.StringOutput {
	return o.ApplyT(func(v SavedFiltersFilter) string { return v.WorkspaceToken }).(pulumi.StringOutput)
}

type SavedFiltersFilterArrayOutput struct{ *pulumi.OutputState }

func (SavedFiltersFilterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]SavedFiltersFilter)(nil)).Elem()
}

func (o SavedFiltersFilterArrayOutput) ToSavedFiltersFilterArrayOutput() SavedFiltersFilterArrayOutput {
	return o
}

func (o SavedFiltersFilterArrayOutput) ToSavedFiltersFilterArrayOutputWithContext(ctx context.Context) SavedFiltersFilterArrayOutput {
	return o
}

func (o SavedFiltersFilterArrayOutput) Index(i pulumi.IntInput) SavedFiltersFilterOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) SavedFiltersFilter {
		return vs[0].([]SavedFiltersFilter)[vs[1].(int)]
	}).(SavedFiltersFilterOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SavedFiltersFilterInput)(nil)).Elem(), SavedFiltersFilterArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*SavedFiltersFilterArrayInput)(nil)).Elem(), SavedFiltersFilterArray{})
	pulumi.RegisterOutputType(SavedFiltersFilterOutput{})
	pulumi.RegisterOutputType(SavedFiltersFilterArrayOutput{})
}
