// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vantage.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class FolderState extends com.pulumi.resources.ResourceArgs {

    public static final FolderState Empty = new FolderState();

    /**
     * Token of the folder&#39;s parent folder
     * 
     */
    @Import(name="parentFolderToken")
    private @Nullable Output<String> parentFolderToken;

    /**
     * @return Token of the folder&#39;s parent folder
     * 
     */
    public Optional<Output<String>> parentFolderToken() {
        return Optional.ofNullable(this.parentFolderToken);
    }

    /**
     * Title of the folder
     * 
     */
    @Import(name="title")
    private @Nullable Output<String> title;

    /**
     * @return Title of the folder
     * 
     */
    public Optional<Output<String>> title() {
        return Optional.ofNullable(this.title);
    }

    /**
     * Unique folder identifier
     * 
     */
    @Import(name="token")
    private @Nullable Output<String> token;

    /**
     * @return Unique folder identifier
     * 
     */
    public Optional<Output<String>> token() {
        return Optional.ofNullable(this.token);
    }

    /**
     * Workspace token to add the cost report to.
     * 
     */
    @Import(name="workspaceToken")
    private @Nullable Output<String> workspaceToken;

    /**
     * @return Workspace token to add the cost report to.
     * 
     */
    public Optional<Output<String>> workspaceToken() {
        return Optional.ofNullable(this.workspaceToken);
    }

    private FolderState() {}

    private FolderState(FolderState $) {
        this.parentFolderToken = $.parentFolderToken;
        this.title = $.title;
        this.token = $.token;
        this.workspaceToken = $.workspaceToken;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(FolderState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private FolderState $;

        public Builder() {
            $ = new FolderState();
        }

        public Builder(FolderState defaults) {
            $ = new FolderState(Objects.requireNonNull(defaults));
        }

        /**
         * @param parentFolderToken Token of the folder&#39;s parent folder
         * 
         * @return builder
         * 
         */
        public Builder parentFolderToken(@Nullable Output<String> parentFolderToken) {
            $.parentFolderToken = parentFolderToken;
            return this;
        }

        /**
         * @param parentFolderToken Token of the folder&#39;s parent folder
         * 
         * @return builder
         * 
         */
        public Builder parentFolderToken(String parentFolderToken) {
            return parentFolderToken(Output.of(parentFolderToken));
        }

        /**
         * @param title Title of the folder
         * 
         * @return builder
         * 
         */
        public Builder title(@Nullable Output<String> title) {
            $.title = title;
            return this;
        }

        /**
         * @param title Title of the folder
         * 
         * @return builder
         * 
         */
        public Builder title(String title) {
            return title(Output.of(title));
        }

        /**
         * @param token Unique folder identifier
         * 
         * @return builder
         * 
         */
        public Builder token(@Nullable Output<String> token) {
            $.token = token;
            return this;
        }

        /**
         * @param token Unique folder identifier
         * 
         * @return builder
         * 
         */
        public Builder token(String token) {
            return token(Output.of(token));
        }

        /**
         * @param workspaceToken Workspace token to add the cost report to.
         * 
         * @return builder
         * 
         */
        public Builder workspaceToken(@Nullable Output<String> workspaceToken) {
            $.workspaceToken = workspaceToken;
            return this;
        }

        /**
         * @param workspaceToken Workspace token to add the cost report to.
         * 
         * @return builder
         * 
         */
        public Builder workspaceToken(String workspaceToken) {
            return workspaceToken(Output.of(workspaceToken));
        }

        public FolderState build() {
            return $;
        }
    }

}
