// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Vantage.Outputs
{

    [OutputType]
    public sealed class GetCostReportsCostReportResult
    {
        public readonly string Filter;
        public readonly string FolderToken;
        public readonly ImmutableArray<string> SavedFilterTokens;
        public readonly string Title;
        public readonly string Token;
        public readonly string WorkspaceToken;

        [OutputConstructor]
        private GetCostReportsCostReportResult(
            string filter,

            string folderToken,

            ImmutableArray<string> savedFilterTokens,

            string title,

            string token,

            string workspaceToken)
        {
            Filter = filter;
            FolderToken = folderToken;
            SavedFilterTokens = savedFilterTokens;
            Title = title;
            Token = token;
            WorkspaceToken = workspaceToken;
        }
    }
}
