// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Vantage.Outputs
{

    [OutputType]
    public sealed class GetDashboardsDashboardResult
    {
        public readonly string DateBin;
        public readonly string DateInterval;
        public readonly string EndDate;
        public readonly string StartDate;
        public readonly string Title;
        public readonly string Token;
        public readonly ImmutableArray<string> WidgetTokens;
        public readonly string WorkspaceToken;

        [OutputConstructor]
        private GetDashboardsDashboardResult(
            string dateBin,

            string dateInterval,

            string endDate,

            string startDate,

            string title,

            string token,

            ImmutableArray<string> widgetTokens,

            string workspaceToken)
        {
            DateBin = dateBin;
            DateInterval = dateInterval;
            EndDate = endDate;
            StartDate = startDate;
            Title = title;
            Token = token;
            WidgetTokens = widgetTokens;
            WorkspaceToken = workspaceToken;
        }
    }
}
