// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Vantage.Outputs
{

    [OutputType]
    public sealed class GetTeamsTeamResult
    {
        public readonly string Description;
        public readonly string Name;
        public readonly string Token;
        public readonly ImmutableArray<string> UserEmails;
        public readonly ImmutableArray<string> UserTokens;
        public readonly ImmutableArray<string> WorkspaceTokens;

        [OutputConstructor]
        private GetTeamsTeamResult(
            string description,

            string name,

            string token,

            ImmutableArray<string> userEmails,

            ImmutableArray<string> userTokens,

            ImmutableArray<string> workspaceTokens)
        {
            Description = description;
            Name = name;
            Token = token;
            UserEmails = userEmails;
            UserTokens = userTokens;
            WorkspaceTokens = workspaceTokens;
        }
    }
}
