// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Vantage
{
    public static class GetAwsProviderInfo
    {
        public static Task<GetAwsProviderInfoResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAwsProviderInfoResult>("vantage:index/getAwsProviderInfo:getAwsProviderInfo", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetAwsProviderInfoResult
    {
        /// <summary>
        /// The policy that allows Vantage to list and describe resources from your AWS account.
        /// </summary>
        public readonly string AdditionalResourcesPolicy;
        /// <summary>
        /// The policy that allows Vantage to manage autopilot.
        /// </summary>
        public readonly string AutopilotPolicy;
        /// <summary>
        /// The policy that allows Vantage to retrieve cloudwatch metrics from your AWS account.
        /// </summary>
        public readonly string CloudwatchMetricsPolicy;
        /// <summary>
        /// The Vantage external ID to authenticate your account.
        /// </summary>
        public readonly string ExternalId;
        /// <summary>
        /// The IAM role that Vantage assumes into your account.
        /// </summary>
        public readonly string IamRoleArn;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The policy that allows Vantage to manage autopilot.
        /// </summary>
        public readonly string RootPolicy;

        [OutputConstructor]
        private GetAwsProviderInfoResult(
            string additionalResourcesPolicy,

            string autopilotPolicy,

            string cloudwatchMetricsPolicy,

            string externalId,

            string iamRoleArn,

            string id,

            string rootPolicy)
        {
            AdditionalResourcesPolicy = additionalResourcesPolicy;
            AutopilotPolicy = autopilotPolicy;
            CloudwatchMetricsPolicy = cloudwatchMetricsPolicy;
            ExternalId = externalId;
            IamRoleArn = iamRoleArn;
            Id = id;
            RootPolicy = rootPolicy;
        }
    }
}
