// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Vantage
{
    public static class GetCostReports
    {
        public static Task<GetCostReportsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCostReportsResult>("vantage:index/getCostReports:getCostReports", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetCostReportsResult
    {
        public readonly ImmutableArray<Outputs.GetCostReportsCostReportResult> CostReports;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetCostReportsResult(
            ImmutableArray<Outputs.GetCostReportsCostReportResult> costReports,

            string id)
        {
            CostReports = costReports;
            Id = id;
        }
    }
}
