// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Vantage
{
    public static class GetWorkspaces
    {
        public static Task<GetWorkspacesResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetWorkspacesResult>("vantage:index/getWorkspaces:getWorkspaces", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetWorkspacesResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetWorkspacesWorkspaceResult> Workspaces;

        [OutputConstructor]
        private GetWorkspacesResult(
            string id,

            ImmutableArray<Outputs.GetWorkspacesWorkspaceResult> workspaces)
        {
            Id = id;
            Workspaces = workspaces;
        }
    }
}
