// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Vantage
{
    public static class SavedFilters
    {
        public static Task<SavedFiltersResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<SavedFiltersResult>("vantage:index/savedFilters:SavedFilters", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class SavedFiltersResult
    {
        public readonly ImmutableArray<Outputs.SavedFiltersFilterResult> Filters;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private SavedFiltersResult(
            ImmutableArray<Outputs.SavedFiltersFilterResult> filters,

            string id)
        {
            Filters = filters;
            Id = id;
        }
    }
}
