// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vantage.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.vantage.outputs.GetAccessGrantsAccessGrant;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetAccessGrantsResult {
    private List<GetAccessGrantsAccessGrant> accessGrants;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;

    private GetAccessGrantsResult() {}
    public List<GetAccessGrantsAccessGrant> accessGrants() {
        return this.accessGrants;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccessGrantsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetAccessGrantsAccessGrant> accessGrants;
        private String id;
        public Builder() {}
        public Builder(GetAccessGrantsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accessGrants = defaults.accessGrants;
    	      this.id = defaults.id;
        }

        @CustomType.Setter
        public Builder accessGrants(List<GetAccessGrantsAccessGrant> accessGrants) {
            this.accessGrants = Objects.requireNonNull(accessGrants);
            return this;
        }
        public Builder accessGrants(GetAccessGrantsAccessGrant... accessGrants) {
            return accessGrants(List.of(accessGrants));
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        public GetAccessGrantsResult build() {
            final var o = new GetAccessGrantsResult();
            o.accessGrants = accessGrants;
            o.id = id;
            return o;
        }
    }
}
