// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vantage.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.vantage.outputs.GetCostReportsCostReport;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetCostReportsResult {
    private List<GetCostReportsCostReport> costReports;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;

    private GetCostReportsResult() {}
    public List<GetCostReportsCostReport> costReports() {
        return this.costReports;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetCostReportsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetCostReportsCostReport> costReports;
        private String id;
        public Builder() {}
        public Builder(GetCostReportsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.costReports = defaults.costReports;
    	      this.id = defaults.id;
        }

        @CustomType.Setter
        public Builder costReports(List<GetCostReportsCostReport> costReports) {
            this.costReports = Objects.requireNonNull(costReports);
            return this;
        }
        public Builder costReports(GetCostReportsCostReport... costReports) {
            return costReports(List.of(costReports));
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        public GetCostReportsResult build() {
            final var o = new GetCostReportsResult();
            o.costReports = costReports;
            o.id = id;
            return o;
        }
    }
}
