// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vantage.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetDashboardsDashboard {
    private String dateBin;
    private String dateInterval;
    private String endDate;
    private String startDate;
    private String title;
    private String token;
    private List<String> widgetTokens;
    private String workspaceToken;

    private GetDashboardsDashboard() {}
    public String dateBin() {
        return this.dateBin;
    }
    public String dateInterval() {
        return this.dateInterval;
    }
    public String endDate() {
        return this.endDate;
    }
    public String startDate() {
        return this.startDate;
    }
    public String title() {
        return this.title;
    }
    public String token() {
        return this.token;
    }
    public List<String> widgetTokens() {
        return this.widgetTokens;
    }
    public String workspaceToken() {
        return this.workspaceToken;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDashboardsDashboard defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String dateBin;
        private String dateInterval;
        private String endDate;
        private String startDate;
        private String title;
        private String token;
        private List<String> widgetTokens;
        private String workspaceToken;
        public Builder() {}
        public Builder(GetDashboardsDashboard defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dateBin = defaults.dateBin;
    	      this.dateInterval = defaults.dateInterval;
    	      this.endDate = defaults.endDate;
    	      this.startDate = defaults.startDate;
    	      this.title = defaults.title;
    	      this.token = defaults.token;
    	      this.widgetTokens = defaults.widgetTokens;
    	      this.workspaceToken = defaults.workspaceToken;
        }

        @CustomType.Setter
        public Builder dateBin(String dateBin) {
            this.dateBin = Objects.requireNonNull(dateBin);
            return this;
        }
        @CustomType.Setter
        public Builder dateInterval(String dateInterval) {
            this.dateInterval = Objects.requireNonNull(dateInterval);
            return this;
        }
        @CustomType.Setter
        public Builder endDate(String endDate) {
            this.endDate = Objects.requireNonNull(endDate);
            return this;
        }
        @CustomType.Setter
        public Builder startDate(String startDate) {
            this.startDate = Objects.requireNonNull(startDate);
            return this;
        }
        @CustomType.Setter
        public Builder title(String title) {
            this.title = Objects.requireNonNull(title);
            return this;
        }
        @CustomType.Setter
        public Builder token(String token) {
            this.token = Objects.requireNonNull(token);
            return this;
        }
        @CustomType.Setter
        public Builder widgetTokens(List<String> widgetTokens) {
            this.widgetTokens = Objects.requireNonNull(widgetTokens);
            return this;
        }
        public Builder widgetTokens(String... widgetTokens) {
            return widgetTokens(List.of(widgetTokens));
        }
        @CustomType.Setter
        public Builder workspaceToken(String workspaceToken) {
            this.workspaceToken = Objects.requireNonNull(workspaceToken);
            return this;
        }
        public GetDashboardsDashboard build() {
            final var o = new GetDashboardsDashboard();
            o.dateBin = dateBin;
            o.dateInterval = dateInterval;
            o.endDate = endDate;
            o.startDate = startDate;
            o.title = title;
            o.token = token;
            o.widgetTokens = widgetTokens;
            o.workspaceToken = workspaceToken;
            return o;
        }
    }
}
