// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vantage.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.vantage.outputs.GetDashboardsDashboard;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetDashboardsResult {
    private List<GetDashboardsDashboard> dashboards;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;

    private GetDashboardsResult() {}
    public List<GetDashboardsDashboard> dashboards() {
        return this.dashboards;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDashboardsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetDashboardsDashboard> dashboards;
        private String id;
        public Builder() {}
        public Builder(GetDashboardsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dashboards = defaults.dashboards;
    	      this.id = defaults.id;
        }

        @CustomType.Setter
        public Builder dashboards(List<GetDashboardsDashboard> dashboards) {
            this.dashboards = Objects.requireNonNull(dashboards);
            return this;
        }
        public Builder dashboards(GetDashboardsDashboard... dashboards) {
            return dashboards(List.of(dashboards));
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        public GetDashboardsResult build() {
            final var o = new GetDashboardsResult();
            o.dashboards = dashboards;
            o.id = id;
            return o;
        }
    }
}
