// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vantage.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.vantage.outputs.GetWorkspacesWorkspace;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetWorkspacesResult {
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private List<GetWorkspacesWorkspace> workspaces;

    private GetWorkspacesResult() {}
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public List<GetWorkspacesWorkspace> workspaces() {
        return this.workspaces;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetWorkspacesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private List<GetWorkspacesWorkspace> workspaces;
        public Builder() {}
        public Builder(GetWorkspacesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.workspaces = defaults.workspaces;
        }

        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder workspaces(List<GetWorkspacesWorkspace> workspaces) {
            this.workspaces = Objects.requireNonNull(workspaces);
            return this;
        }
        public Builder workspaces(GetWorkspacesWorkspace... workspaces) {
            return workspaces(List.of(workspaces));
        }
        public GetWorkspacesResult build() {
            final var o = new GetWorkspacesResult();
            o.id = id;
            o.workspaces = workspaces;
            return o;
        }
    }
}
