// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vantage.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetWorkspacesWorkspace {
    private String name;
    private String token;

    private GetWorkspacesWorkspace() {}
    public String name() {
        return this.name;
    }
    public String token() {
        return this.token;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetWorkspacesWorkspace defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String name;
        private String token;
        public Builder() {}
        public Builder(GetWorkspacesWorkspace defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.name = defaults.name;
    	      this.token = defaults.token;
        }

        @CustomType.Setter
        public Builder name(String name) {
            this.name = Objects.requireNonNull(name);
            return this;
        }
        @CustomType.Setter
        public Builder token(String token) {
            this.token = Objects.requireNonNull(token);
            return this;
        }
        public GetWorkspacesWorkspace build() {
            final var o = new GetWorkspacesWorkspace();
            o.name = name;
            o.token = token;
            return o;
        }
    }
}
