// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vantage.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.vantage.outputs.SavedFiltersFilter;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class SavedFiltersResult {
    private List<SavedFiltersFilter> filters;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;

    private SavedFiltersResult() {}
    public List<SavedFiltersFilter> filters() {
        return this.filters;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SavedFiltersResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<SavedFiltersFilter> filters;
        private String id;
        public Builder() {}
        public Builder(SavedFiltersResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.filters = defaults.filters;
    	      this.id = defaults.id;
        }

        @CustomType.Setter
        public Builder filters(List<SavedFiltersFilter> filters) {
            this.filters = Objects.requireNonNull(filters);
            return this;
        }
        public Builder filters(SavedFiltersFilter... filters) {
            return filters(List.of(filters));
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        public SavedFiltersResult build() {
            final var o = new SavedFiltersResult();
            o.filters = filters;
            o.id = id;
            return o;
        }
    }
}
