// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.vantage.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class SavedFiltersFilter {
    private List<String> costReportTokens;
    private String title;
    private String token;
    private String workspaceToken;

    private SavedFiltersFilter() {}
    public List<String> costReportTokens() {
        return this.costReportTokens;
    }
    public String title() {
        return this.title;
    }
    public String token() {
        return this.token;
    }
    public String workspaceToken() {
        return this.workspaceToken;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(SavedFiltersFilter defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<String> costReportTokens;
        private String title;
        private String token;
        private String workspaceToken;
        public Builder() {}
        public Builder(SavedFiltersFilter defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.costReportTokens = defaults.costReportTokens;
    	      this.title = defaults.title;
    	      this.token = defaults.token;
    	      this.workspaceToken = defaults.workspaceToken;
        }

        @CustomType.Setter
        public Builder costReportTokens(List<String> costReportTokens) {
            this.costReportTokens = Objects.requireNonNull(costReportTokens);
            return this;
        }
        public Builder costReportTokens(String... costReportTokens) {
            return costReportTokens(List.of(costReportTokens));
        }
        @CustomType.Setter
        public Builder title(String title) {
            this.title = Objects.requireNonNull(title);
            return this;
        }
        @CustomType.Setter
        public Builder token(String token) {
            this.token = Objects.requireNonNull(token);
            return this;
        }
        @CustomType.Setter
        public Builder workspaceToken(String workspaceToken) {
            this.workspaceToken = Objects.requireNonNull(workspaceToken);
            return this;
        }
        public SavedFiltersFilter build() {
            final var o = new SavedFiltersFilter();
            o.costReportTokens = costReportTokens;
            o.title = title;
            o.token = token;
            o.workspaceToken = workspaceToken;
            return o;
        }
    }
}
