// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getAwsProviderInfo(opts?: pulumi.InvokeOptions): Promise<GetAwsProviderInfoResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("vantage:index/getAwsProviderInfo:getAwsProviderInfo", {
    }, opts);
}

/**
 * A collection of values returned by getAwsProviderInfo.
 */
export interface GetAwsProviderInfoResult {
    readonly additionalResourcesPolicy: string;
    readonly autopilotPolicy: string;
    readonly cloudwatchMetricsPolicy: string;
    readonly externalId: string;
    readonly iamRoleArn: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly rootPolicy: string;
}
