// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manages a Segment.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as vantage from "@lbrlabs/pulumi-vantage";
 *
 * const demoSegment = new vantage.Segment("demoSegment", {
 *     description: "This is still a demo segment",
 *     filter: "(costs.provider = 'aws' AND tags.name = NULL)",
 *     priority: 50,
 *     title: "Demo Segment",
 *     trackUnallocated: false,
 * });
 * ```
 */
export class Segment extends pulumi.CustomResource {
    /**
     * Get an existing Segment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SegmentState, opts?: pulumi.CustomResourceOptions): Segment {
        return new Segment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'vantage:index/segment:Segment';

    /**
     * Returns true if the given object is an instance of Segment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Segment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Segment.__pulumiType;
    }

    /**
     * The description of the Segment.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The filter query language to apply to the Segment. Additional documentation available at https://docs.vantage.sh/vql.
     */
    public readonly filter!: pulumi.Output<string>;
    /**
     * The token of the parent Segment this new Segment belongs to. Determines the Workspace the segment is assigned to.
     */
    public readonly parentSegmentToken!: pulumi.Output<string>;
    /**
     * The priority of the Segment.
     */
    public readonly priority!: pulumi.Output<number>;
    /**
     * The title of the Segment.
     */
    public readonly title!: pulumi.Output<string>;
    /**
     * Unique segment identifier
     */
    public /*out*/ readonly token!: pulumi.Output<string>;
    /**
     * Whether or not to track unallocated resources in this Segment.
     */
    public readonly trackUnallocated!: pulumi.Output<boolean>;
    /**
     * Workspace token to add the segment to.
     */
    public readonly workspaceToken!: pulumi.Output<string>;

    /**
     * Create a Segment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SegmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SegmentArgs | SegmentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SegmentState | undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["filter"] = state ? state.filter : undefined;
            resourceInputs["parentSegmentToken"] = state ? state.parentSegmentToken : undefined;
            resourceInputs["priority"] = state ? state.priority : undefined;
            resourceInputs["title"] = state ? state.title : undefined;
            resourceInputs["token"] = state ? state.token : undefined;
            resourceInputs["trackUnallocated"] = state ? state.trackUnallocated : undefined;
            resourceInputs["workspaceToken"] = state ? state.workspaceToken : undefined;
        } else {
            const args = argsOrState as SegmentArgs | undefined;
            if ((!args || args.title === undefined) && !opts.urn) {
                throw new Error("Missing required property 'title'");
            }
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["filter"] = args ? args.filter : undefined;
            resourceInputs["parentSegmentToken"] = args ? args.parentSegmentToken : undefined;
            resourceInputs["priority"] = args ? args.priority : undefined;
            resourceInputs["title"] = args ? args.title : undefined;
            resourceInputs["trackUnallocated"] = args ? args.trackUnallocated : undefined;
            resourceInputs["workspaceToken"] = args ? args.workspaceToken : undefined;
            resourceInputs["token"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Segment.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Segment resources.
 */
export interface SegmentState {
    /**
     * The description of the Segment.
     */
    description?: pulumi.Input<string>;
    /**
     * The filter query language to apply to the Segment. Additional documentation available at https://docs.vantage.sh/vql.
     */
    filter?: pulumi.Input<string>;
    /**
     * The token of the parent Segment this new Segment belongs to. Determines the Workspace the segment is assigned to.
     */
    parentSegmentToken?: pulumi.Input<string>;
    /**
     * The priority of the Segment.
     */
    priority?: pulumi.Input<number>;
    /**
     * The title of the Segment.
     */
    title?: pulumi.Input<string>;
    /**
     * Unique segment identifier
     */
    token?: pulumi.Input<string>;
    /**
     * Whether or not to track unallocated resources in this Segment.
     */
    trackUnallocated?: pulumi.Input<boolean>;
    /**
     * Workspace token to add the segment to.
     */
    workspaceToken?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Segment resource.
 */
export interface SegmentArgs {
    /**
     * The description of the Segment.
     */
    description?: pulumi.Input<string>;
    /**
     * The filter query language to apply to the Segment. Additional documentation available at https://docs.vantage.sh/vql.
     */
    filter?: pulumi.Input<string>;
    /**
     * The token of the parent Segment this new Segment belongs to. Determines the Workspace the segment is assigned to.
     */
    parentSegmentToken?: pulumi.Input<string>;
    /**
     * The priority of the Segment.
     */
    priority?: pulumi.Input<number>;
    /**
     * The title of the Segment.
     */
    title: pulumi.Input<string>;
    /**
     * Whether or not to track unallocated resources in this Segment.
     */
    trackUnallocated?: pulumi.Input<boolean>;
    /**
     * Workspace token to add the segment to.
     */
    workspaceToken?: pulumi.Input<string>;
}
